client_config_backend: settings
client_config:
  client_id: "236819335465-43d7n42tsg7ompebj9cf7cb3c5vg5lvj.apps.googleusercontent.com"
  client_secret: "JxTRsQIpvPZIhoJvHr_kKDCJ"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file