client_config_backend: settings
client_config:
  client_id: "840149243243-mnad8hmt772v6vte681c7fmf3f316un2.apps.googleusercontent.com"
  client_secret: "BmGe8ltS9jffe67UChFnS3JH"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file